### ISSUE TITLE
Bug when taking Teleporter or picking up gold

### ISSUE THREAD

**Issue by uberEpicDonkey** [SUHAFUTI/Glorious-Console-Adventure#14]
It plays the sound and "removes" the item. When cave is revisited, items reappear visually.

**Comment by uberEpicDonkey** [comment]
Teleporters should ofc. stay.

**Comment by uberEpicDonkey** [comment]
Gold fixed, tp works in a first take state, but needs to be persisted visually.

**Comment by iyousifi** [comment]
fixed with 23334f5129c7584f48023561162dc90b1dcd31bb
