### ISSUE TITLE
We need to refactor maps coordinates

### ISSUE THREAD

**Issue by uberEpicDonkey** [SUHAFUTI/Glorious-Console-Adventure#15]
In it's current state maps adjacent to each other doesn't know about it when entered from different entrances. 
We need to create a map metrics instead.

**Comment by iyousifi** [comment]
Review 25e0da725329ad0ae56ccb51076b02674eccc79e (latest commit in that epic feature branch) and merge to master to win! Also close this issue :D

**Comment by uberEpicDonkey** [comment]
Fixed in 25e0da725329ad0ae56ccb51076b02674eccc79e
