### ISSUE TITLE
Need to validate start location

### ISSUE THREAD

**Issue by uberEpicDonkey** [SUHAFUTI/Glorious-Console-Adventure#3]
Sometimes the start location, due to the way it works, accidently traps the player in a pocket in the wall. We need to validate if the start location is part of the main room

**Comment by iyousifi** [comment]
Simple solution would be to move Hero to the middle and test if it's empty then gradually shift to one direction until a valid location is found.

**Comment by uberEpicDonkey** [comment]
Should be sufficient, another option would be to make a surrounding block check or a combo.

**Comment by uberEpicDonkey** [comment]
Added offset to get valid start location. 37424656bdb9ecdfa74d234c2ba65c9381b75d44
